version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    # For dev, this setup serves frontend on :8080 and backend on :3000
